name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: lint
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: build
      env:
        CI: true
